"""Session context abstraction for provider-level session resumption.

CLI provider: stores session_id (~50 bytes), SDK handles context.
API provider: stores message_history, compacted when threshold exceeded.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

MAX_REFINEMENT_TURNS = 10
MAX_SESSION_CONTEXT_BYTES = 256_000  # 256KB hard cap per branch
COMPACTION_KEEP_PAIRS = 4  # keep last N turn pairs after compaction


@dataclass
class SessionContext:
    """Provider-agnostic session state."""
    session_id: str | None = None
    message_history: list[dict] | None = None
    provider_type: str = ""
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    turn_count: int = 0

    def to_dict(self) -> dict:
        return {
            "session_id": self.session_id,
            "message_history": self.message_history,
            "provider_type": self.provider_type,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "turn_count": self.turn_count,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "SessionContext":
        created = data.get("created_at")
        if created and isinstance(created, str):
            created = datetime.fromisoformat(created)
        return cls(
            session_id=data.get("session_id"),
            message_history=data.get("message_history"),
            provider_type=data.get("provider_type", ""),
            created_at=created or datetime.now(timezone.utc),
            turn_count=data.get("turn_count", 0),
        )


def needs_compaction(session: SessionContext) -> bool:
    """Check if session needs compaction (turn count or byte size)."""
    if session.turn_count > MAX_REFINEMENT_TURNS:
        return True
    if session.message_history:
        size = len(json.dumps(session.message_history))
        if size > MAX_SESSION_CONTEXT_BYTES:
            return True
    return False


async def compact_session(
    session: SessionContext,
    provider,
) -> SessionContext:
    """Compact session history by summarizing old turns.

    Keeps system message + summary + last 4 turn pairs.
    Summary generated by Haiku 4.5. On failure: return uncompacted.
    """
    if not needs_compaction(session):
        return session

    history = session.message_history
    if not history or len(history) < 3:
        return session

    keep_count = COMPACTION_KEEP_PAIRS * 2  # pairs → individual messages
    old_turns = history[1:-keep_count] if len(history) > keep_count + 1 else []

    if not old_turns:
        return session

    try:
        summary = await provider.complete(
            system="Summarize this conversation concisely, preserving all decisions and constraints.",
            user=json.dumps(old_turns),
            model="claude-haiku-4-5",
        )
    except Exception:
        logger.warning("Session compaction failed, continuing with full history")
        return session

    compacted_history = [
        history[0],  # system message
        {"role": "user", "content": f"[Previous refinement context]\n{summary}"},
        {"role": "assistant", "content": "Understood. I have the full context."},
        *history[-keep_count:],
    ]

    return SessionContext(
        session_id=session.session_id,
        message_history=compacted_history,
        provider_type=session.provider_type,
        created_at=session.created_at,
        turn_count=session.turn_count,
    )
