/**
 * Color utilities for taxonomy visualization.
 *
 * Replaces `constants/patterns.ts` — colors now come from the API
 * (generated by the backend's OKLab system). This module provides
 * only the score-to-color mapping and a fallback for null API colors.
 */

/** Default color for nodes/families without an API-assigned color. */
const FALLBACK_COLOR = '#7a7a9e';

/** Score-to-color mapping using design system tokens. */
export function scoreColor(score: number | null): string {
  if (score == null || score <= 0) return 'var(--color-text-dim)';
  if (score >= 9.0) return 'var(--color-neon-green)';
  if (score >= 7.0) return 'var(--color-neon-cyan)';
  if (score >= 4.0) return 'var(--color-neon-yellow)';
  return 'var(--color-neon-red)';
}

/** Resolve a taxonomy color, falling back to neutral gray. */
export function taxonomyColor(color: string | null | undefined): string {
  return color ?? FALLBACK_COLOR;
}

/** Q_system health color for StatusBar badge. */
export function qHealthColor(qSystem: number | null): string {
  if (qSystem == null) return 'var(--color-text-dim)';
  if (qSystem >= 0.8) return 'var(--color-neon-green)';
  if (qSystem >= 0.6) return 'var(--color-neon-cyan)';
  if (qSystem >= 0.4) return 'var(--color-neon-yellow)';
  return 'var(--color-neon-red)';
}
